# Batch Service - STAGING environment overrides
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/batch_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate

app:
  aws:
    s3:
      reports-bucket: amazon-demo-stage-reports
      endpoint: "http://localstack:4566"
